<div id="footerUpper" class="">
				<div class="content">
					<span class="gold">斯特拉斯艾伦学校 Strathallan School</span>
					<br />地址：英国苏格兰 Forgandenny, Perth PH2 9EG Scotland UK 
					<br />电话： +44 (0)1738 812 546 传真： +44 (0)1738 812 549
<br />中国咨询电话：(0755) 2644 4700					
<br />苏格兰非盈利性组织编号 SC008903<br />
					<!-- <div class="links"><a href="#">隐私保护 </a> // <a href="#"> Site Map </a> // <a href="#"> Accessibility</a></div> -->
					
				          Website developed by: Meridian China | 技术支持: <b>麦氏国际</b>
					

					<div class="opportunities">
						<h2>Opportunities for all to excel</h2>						
						<a href="mailto:uk_boarding_school@163.com" title="发送邮件"><img src="https://gs.meridian-mkt.cn/002/images/icons/email-icon1.png" tppabs="http://www.strathallan.co.uk/images/icons/email-icon1.png" width="30" height="30" alt="#" /></a>
						<!--
						<a href="#"><img src="/images/icons/twitter.png" width="30" height="30" alt="#" /></a>
						<a href="#"><img src="/images/icons/youtube.png" width="30" height="30" alt="#" /></a>	
						-->					
					</div>
				</div>
			</div><!-- end of footerUpper -->
