<div id="footerLower">
				<div class="content">
					<span class="quickLink">快速链接</span>
					<div class="quickLinkOpen">打开</div>
					<div class="quickLinkClose">关闭</div>
				<div class="bgArrow"></div>
				</div>
			</div><!-- end of footerLower -->
<div id="overlayWrapper">
				<div id="overlay">
				
					<div class="linkColWrappers">
					
						<div class="linkCol">
						
																													
							<h2>关于学校</h2>
							<ul>
								<li><a href="/184_History.html" tppabs="http://www.strathallan.co.uk/184_History.html">历史</a></li>
								
								<li><a href="/191_Facilities.html" tppabs="http://www.strathallan.co.uk/sitemap.php">设施</a></li>
							</ul>
						</div>
					
						<div class="linkCol">
							<h2>入学申请</h2>
							<ul>
								<li><a href="/196_HowtoApply.html" tppabs="http://www.strathallan.co.uk/196_HowtoApply.html">申请流程</a></li>
								<li><a href="/registration/registration.php.htm" tppabs="http://www.strathallan.co.uk/registration/registration.php">申请表格</a></li>
								<li><a href="/192_Admissions.html" tppabs="http://www.strathallan.co.uk/192_Admissions.html">入学申请</a></li>
								<li><a href="/contact.php.htm" tppabs="http://www.strathallan.co.uk/contact.php">预约参观</a></li>
								<li><a href="/197_Scholarships.html" tppabs="http://www.strathallan.co.uk/197_Scholarships.html">奖学金</a></li>
							</ul>
							
						</div>
					
						<div class="linkColMap">
							<h2>地理位置</h2>
							<div class="map">
								<a href="/contact.php.htm" tppabs="http://www.strathallan.co.uk/contact.php"><img src="https://gs.meridian-mkt.cn/002/images/map-footer.jpg" tppabs="http://www.strathallan.co.uk/images/map-footer.jpg" alt=""/></a>
							</div>
							<h2>社交网络</h2>
							<a href="http://www.facebook.com/pages/Strathallan-School/140545376036236" target="_blank"><img src="https://gs.meridian-mkt.cn/002/images/icons/facebook.png" tppabs="http://www.strathallan.co.uk/images/icons/facebook.png" width="30" height="30" alt="#" /></a>
							<a href="mailto:uk_boarding_school@163.com" title="Email Us"><img src="https://gs.meridian-mkt.cn/002/images/icons/email-icon1.png" tppabs="http://www.strathallan.co.uk/images/icons/email-icon1.png" width="30" height="30" alt="#" /></a>
							<!--
							<a href="#"><img src="/images/icons/twitter.png" width="30" height="30" alt="#" /></a>
							<a href="#"><img src="/images/icons/youtube.png" width="30" height="30" alt="#" /></a>
							-->
						</div>
						
					</div>
					
				</div><!-- end of overlay -->
			</div><!-- end of overlayWrapper -->

<!-- Plugins -->
		<script src="js/jquery.selectbox-0.2.min.js" tppabs="http://www.strathallan.co.uk/js/jquery.selectbox-0.2.min.js"></script>
		<script src="js/date.format.js" tppabs="http://www.strathallan.co.uk/js/date.format.js"></script>
		<script src="js/jquery.jscrollpane.min.js" tppabs="http://www.strathallan.co.uk/js/jquery.jscrollpane.min.js"></script> 
		<script src="js/jquery.mousewheel.js" tppabs="http://www.strathallan.co.uk/js/jquery.mousewheel.js"></script> 
		<script src="js/fullcalendar.min.js" tppabs="http://www.strathallan.co.uk/js/fullcalendar.min.js"></script>
				
		<script src="js/json2.js" tppabs="http://www.strathallan.co.uk/js/json2.js"></script> 
		<script src="js/fancybox/jquery.fancybox.js" tppabs="http://www.strathallan.co.uk/js/fancybox/jquery.fancybox.js"></script> 
		<script src="js/datepicker/jquery-ui-1.9.2.custom.min.js" tppabs="http://www.strathallan.co.uk/js/datepicker/jquery-ui-1.9.2.custom.min.js"></script> 
		<script src="js/fullbg.js" tppabs="http://www.strathallan.co.uk/js/fullbg.js"></script> 
		<script src="js/jcarousellite.min.js" tppabs="http://www.strathallan.co.uk/js/jcarousellite.min.js"></script> 
		<script src="js/jquery.easing.1.3.js" tppabs="http://www.strathallan.co.uk/js/jquery.easing.1.3.js"></script> 
		<script src="js/cycle.js" tppabs="http://www.strathallan.co.uk/js/cycle.js"></script> 
		<script src="js/jwplayer.js" tppabs="http://www.strathallan.co.uk/js/jwplayer.js"></script>	
		
		<!-- Script -->
		<script src="js/script.js-v4" tppabs="http://www.strathallan.co.uk/js/script.js?v4"></script>
		<script src="js/calendar.js-v6" tppabs="http://www.strathallan.co.uk/js/calendar.js?v6"></script>

			
		<div id="fb-root"></div>
		<script>(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = "../connect.facebook.net/en_US/all.js#xfbml=1"/*tpa=http://connect.facebook.net/en_US/all.js#xfbml=1*/;
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script>
