<div id="headerWrapper">
    <div id="header">
        <a href="/index.htm" tppabs="http://www.strathallan.co.uk/index.php" class="logo"><img src="https://gs.meridian-mkt.cn/002/images/cn/logo.png" tppabs="http://www.strathallan.co.uk/images/logo.png" alt="Strathallan Logo"></a>
        <div id="topNav">
            <ul>
                <li class="spacer"><a href="/index.htm" tppabs="http://www.strathallan.co.uk/index.php">首页</a></li>
                <li class="spacer"><a href="/901_cn.html" tppabs="http://www.strathallan.co.uk/901_cn.html">中国学生</a></li>
                <li class="spacer"><a href="/contact.php.htm" tppabs="http://www.strathallan.co.uk/contact.php">联系我们</a></li>
                <li class="bold"><a href="javascript:decreaseFontSize();" class="decreaseTxt">A</a> <a href="javascript:increaseFontSize();" class="increaseTxt">A</a></li>
            </ul>
        </div>
        <div id="mainNav">
            <ul>
                <li class="active">
                    <a href="/183_AboutUs.html" tppabs="http://www.strathallan.co.uk/183_AboutUs.html">关于我们</a>
                    <div class="dropdown">
                        <ul>
                            <li><a href="/map.php-about.htm" tppabs="http://www.strathallan.co.uk/map.php?about">互动地图</a></li>
                            <li><a href="/231_Location.html" tppabs="http://www.strathallan.co.uk/231_Location.html">地理位置</a></li>
                            <li><a href="/191_Facilities.html" tppabs="http://www.strathallan.co.uk/191_Facilities.html">设施</a></li>
                            <li><a href="/184_History.html" tppabs="http://www.strathallan.co.uk/184_History.html">历史</a></li>
                            <li><a href="/calendar.php.htm" tppabs="http://www.strathallan.co.uk/calendar.php">校历</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a href="/192_Admissions.html" tppabs="http://www.strathallan.co.uk/192_Admissions.html">入学申请</a>
                    <div class="dropdown">
                        <ul>
                            <li><a href="/request-prospectus.php.htm" tppabs="http://www.strathallan.co.uk/request-prospectus.php">索取入学指南</a></li>
                            <li><a href="/registration/registration.php.htm" tppabs="http://www.strathallan.co.uk/registration/registration.php">申请表格</a></li>
                            <li><a href="/196_HowtoApply.html" tppabs="http://www.strathallan.co.uk/196_HowtoApply.html">申请流程</a></li>
                            <li><a href="/197_Scholarships.html" tppabs="http://www.strathallan.co.uk/197_Scholarships.html">奖学金</a></li>
                            <li><a href="/registration/open-mornings.php.htm">开放日</a></li>
                            <li><a href="/199_FeesFeeAssistanceBursaries.html" tppabs="http://www.strathallan.co.uk/199_FeesFeeAssistanceBursaries.html">学费</a></li>
                            <li><a href="/311_TermDates.html" tppabs="http://www.strathallan.co.uk/311_TermDates.html">学期安排</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a href="/200_SchoolLife.html" tppabs="http://www.strathallan.co.uk/200_SchoolLife.html">校园环境</a>
                    <div class="dropdown">
                        <ul>
                            <li><a href="/201_Pupils.html" tppabs="http://www.strathallan.co.uk/201_Pupils.html">学生生活</a></li>
                            <li><a href="/photo-gallery.php.htm" tppabs="http://www.strathallan.co.uk/photo-gallery.php">相册</a></li>
                            <li><a href="/video-gallery.php.htm" tppabs="http://www.strathallan.co.uk/video-gallery.php">视频</a></li>
                            <li><a href="/203_Houses.html" tppabs="http://www.strathallan.co.uk/203_Houses.html">校舍</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a href="/207_Academic.html" tppabs="http://www.strathallan.co.uk/207_Academic.html">教学一览</a>
                    <div class="dropdown">
                        <ul>
                            <li><a href="/208_ExaminationResults.html" tppabs="http://www.strathallan.co.uk/208_ExaminationResults.html">教学成果</a></li>
                            <li><a href="/209_AdditionalSupport.html" tppabs="http://www.strathallan.co.uk/209_AdditionalSupport.html">教学辅导</a></li>
                            <li><a href="/210_CourseChoices.html" tppabs="http://www.strathallan.co.uk/210_CourseChoices.html">课程安排</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a href="/211_OutsidetheClassroom.html" tppabs="http://www.strathallan.co.uk/211_OutsidetheClassroom.html">课余生活</a>
                    <div class="dropdown">
                        <ul>
                            <li><a href="/212_SportsOverview.html" tppabs="http://www.strathallan.co.uk/212_SportsOverview.html">体育运动</a></li>
                            <li><a href="/213_TheArtsOverview.html" tppabs="http://www.strathallan.co.uk/213_TheArtsOverview.html">才艺表演</a></li>
                            <li><a href="/214_ActivitiesOverview.html" tppabs="http://www.strathallan.co.uk/214_ActivitiesOverview.html">其它活动</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a href="/401_IntCamp.html" tppabs="http://www.strathallan.co.uk/401_IntCamp.html">国际夏令营</a>
                </li>
            </ul>
        </div>
    </div>
</div>