		<div id="leftCol" class="faded1">
			
<ul>
        <li class="active"><a href="/222_Strathallians.html" tppabs="http://www.strathallan.co.uk/222_Strathallians.html">校友</a></li>
        
        <li ><a href="/228_StrathallianClub.html" tppabs="http://www.strathallan.co.uk/228_StrathallianClub.html">校友俱乐部</a></li>
    
        
            <li ><a href="/strathallians/whats_on.php.htm" tppabs="http://www.strathallan.co.uk/strathallians/whats_on.php">活动</a></li>
    
        
            
        </ul>		</div>


