<div id="leftCol" class="faded1">
			
<ul>
        <li class="active" ><a href="211_OutsidetheClassroom.html" tppabs="http://www.strathallan.co.uk/211_OutsidetheClassroom.html">课余生活</a></li>
        
        <li ><a href="212_SportsOverview.html" tppabs="http://www.strathallan.co.uk/212_SportsOverview.html">体育运动</a></li>
    
        
            <li ><a href="213_TheArtsOverview.html" tppabs="http://www.strathallan.co.uk/213_TheArtsOverview.html">才艺表演</a></li>
    
        
            <li><a href="214_ActivitiesOverview.html" tppabs="http://www.strathallan.co.uk/214_ActivitiesOverview.html">其它活动</a></li>
    
        
                </ul>		</div>

