	<div id="leftCol" class="faded1">
			
<ul>
        <li  class="active"><a href="/200_SchoolLife.html" tppabs="http://www.strathallan.co.uk/200_SchoolLife.html">校园环境</a></li>
        
        <li><a href="/201_Pupils.html" tppabs="http://www.strathallan.co.uk/201_Pupils.html">学生生活</a></li>
    
        
                    <li ><a href="/photo-gallery.php.htm" tppabs="http://www.strathallan.co.uk/photo-gallery.php">相簿</a></li>
    
        
            <li ><a href="/video-gallery.php.htm" tppabs="http://www.strathallan.co.uk/video-gallery.php">视频</a></li>
    
        
            <li ><a href="/203_Houses.html" tppabs="http://www.strathallan.co.uk/203_Houses.html">校舍</a></li>
    
                
        </ul>		</div>

