<div id="leftCol" class="faded1">
			
<ul>
        <li class="active"><a href="183_AboutUs.html" tppabs="http://www.strathallan.co.uk/183_AboutUs.html">关于我们</a></li>
        
        <li ><a href="map.php-about.htm" tppabs="http://www.strathallan.co.uk/map.php?about">互动地图</a></li>
    
        
            <li ><a href="231_Location.html" tppabs="http://www.strathallan.co.uk/231_Location.html">地理位置</a></li>
    
        
            <li ><a href="191_Facilities.html" tppabs="http://www.strathallan.co.uk/191_Facilities.html">设施</a></li>
    
        
            <li ><a href="184_History.html" tppabs="http://www.strathallan.co.uk/184_History.html">历史</a></li>
    
        
            <li ><a href="calendar.php.htm" tppabs="http://www.strathallan.co.uk/calendar.php">校历</a></li>
    
             
        
        </ul>		</div>
