		<div id="leftCol" class="faded1">
			
<ul>
        <li  class="active"><a href="/192_Admissions.html" tppabs="http://www.strathallan.co.uk/192_Admissions.html">入学申请</a></li>
        
        <li ><a href="/request-prospectus.php.htm" tppabs="http://www.strathallan.co.uk/request-prospectus.php">索取入学指南</a></li>
    
        
            <li ><a href="/registration/registration.php.htm" tppabs="http://www.strathallan.co.uk/registration/registration.php">申请表格</a></li>
    
        
            <li><a href="/196_HowtoApply.html" tppabs="http://www.strathallan.co.uk/196_HowtoApply.html">申请流程</a></li>
    
        
                    <li ><a href="/197_Scholarships.html" tppabs="http://www.strathallan.co.uk/197_Scholarships.html">奖学金</a></li>
    
        
            <li ><a href="/registration/open-mornings.php.htm">学校开放日</a></li>
    
        
            <li ><a href="/199_FeesFeeAssistanceBursaries.html" tppabs="http://www.strathallan.co.uk/199_FeesFeeAssistanceBursaries.html">学费</a></li>
    
        
            <li ><a href="/311_TermDates.html" tppabs="http://www.strathallan.co.uk/311_TermDates.html">学期安排</a></li>
    
        
        </ul>		</div>


