		<div id="leftCol" class="faded1">
			
<ul>
        <li class="active"><a href="/207_Academic.html" tppabs="http://www.strathallan.co.uk/207_Academic.html">教学一览</a></li>
        
        <li ><a href="/208_ExaminationResults.html" tppabs="http://www.strathallan.co.uk/208_ExaminationResults.html">教学成果</a></li>
    
        
            <li ><a href="/209_AdditionalSupport.html" tppabs="http://www.strathallan.co.uk/209_AdditionalSupport.html">教学辅导</a></li>
    
        
            <li ><a href="/210_CourseChoices.html" tppabs="http://www.strathallan.co.uk/210_CourseChoices.html">课程安排</a></li>
    
        
        </ul>		</div>

