<div class="videoItem active">
							<h3>校园采风</h3>
							<div class="vidSmall">
								<a href="photo-gallery.php-id=2.htm" tppabs="http://www.strathallan.co.uk/photo-gallery.php?id=2">
									<div class="overlay"></div><img src="images/image_galleries/thumbs/13470289661314106133SchoolGroundsCustom.jpg" tppabs="http://www.strathallan.co.uk/images/image_galleries/thumbs/13470289661314106133SchoolGroundsCustom.jpg" alt="#" />
								</a>
							</div>
						</div>	
                    	                    <div class="videoItem ">
							<h3>慈善长跑</h3>
							<div class="vidSmall">
								<a href="photo-gallery.php-id=3.htm" tppabs="http://www.strathallan.co.uk/photo-gallery.php?id=3">
									<div class="overlay"></div><img src="images/image_galleries/thumbs/13470289791317029951Web1.jpg" tppabs="http://www.strathallan.co.uk/images/image_galleries/thumbs/13470289791317029951Web1.jpg" alt="#" />
								</a>
							</div>
						</div>	
                    	                    <div class="videoItemRight ">
							<h3>校园生活</h3>
							<div class="vidSmall">
								<a href="photo-gallery.php-id=6.htm" tppabs="http://www.strathallan.co.uk/photo-gallery.php?id=6">
									<div class="overlay"></div><img src="images/image_galleries/thumbs/135031327213170307561.jpg" tppabs="http://www.strathallan.co.uk/images/image_galleries/thumbs/135031327213170307561.jpg" alt="#" />
								</a>
							</div>
						</div>	
                    	                    <div class="videoItem ">
							<h3>Nicol校舍</h3>
							<div class="vidSmall">
								<a href="photo-gallery.php-id=7.htm" tppabs="http://www.strathallan.co.uk/photo-gallery.php?id=7">
									<div class="overlay"></div><img src="images/image_galleries/thumbs/13503133421317030982Gallery6.jpg" tppabs="http://www.strathallan.co.uk/images/image_galleries/thumbs/13503133421317030982Gallery6.jpg" alt="#" />
								</a>
							</div>
						</div>	
                    	                    <div class="videoItem ">
							<h3>Riley校舍</h3>
							<div class="vidSmall">
								<a href="photo-gallery.php-id=8.htm" tppabs="http://www.strathallan.co.uk/photo-gallery.php?id=8">
									<div class="overlay"></div><img src="images/image_galleries/thumbs/13503134201317031042P1050642.jpg" tppabs="http://www.strathallan.co.uk/images/image_galleries/thumbs/13503134201317031042P1050642.jpg" alt="#" />
								</a>
							</div>
						</div>	
                    	                    <div class="videoItemRight ">
							<h3>Ruthven校舍</h3>
							<div class="vidSmall">
								<a href="photo-gallery.php-id=9.htm" tppabs="http://www.strathallan.co.uk/photo-gallery.php?id=9">
									<div class="overlay"></div><img src="images/image_galleries/thumbs/13503135391317031557IMG_0021.jpg" tppabs="http://www.strathallan.co.uk/images/image_galleries/thumbs/13503135391317031557IMG_0021.jpg" alt="#" />
								</a>
							</div>
						</div>	
                    	                    <div class="videoItem ">
							<h3>时装秀</h3>
							<div class="vidSmall">
								<a href="photo-gallery.php-id=12.htm" tppabs="http://www.strathallan.co.uk/photo-gallery.php?id=12">
									<div class="overlay"></div><img src="images/image_galleries/thumbs/13503143941333116084_MG_4105.jpg" tppabs="http://www.strathallan.co.uk/images/image_galleries/thumbs/13503143941333116084_MG_4105.jpg" alt="#" />
								</a>
							</div>
						</div>	
                    	                    <div class="videoItem ">
							<h3>爱丁堡公爵</h3>
							<div class="vidSmall">
								<a href="photo-gallery.php-id=13.htm" tppabs="http://www.strathallan.co.uk/photo-gallery.php?id=13">
									<div class="overlay"></div><img src="images/image_galleries/thumbs/13503144331333452276P1000699.JPG" tppabs="http://www.strathallan.co.uk/images/image_galleries/thumbs/13503144331333452276P1000699.JPG" alt="#" />
								</a>
							</div>
						</div>	
                    	                    <div class="videoItemRight ">
							<h3>历史遗迹</h3>
							<div class="vidSmall">
								<a href="photo-gallery.php-id=14.htm" tppabs="http://www.strathallan.co.uk/photo-gallery.php?id=14">
									<div class="overlay"></div><img src="images/image_galleries/thumbs/13503144681333536590SDC11247.JPG" tppabs="http://www.strathallan.co.uk/images/image_galleries/thumbs/13503144681333536590SDC11247.JPG" alt="#" />
								</a>
							</div>
						</div>	
                    	                    <div class="videoItem ">
							<h3>Freeland校舍</h3>
							<div class="vidSmall">
								<a href="photo-gallery.php-id=15.htm" tppabs="http://www.strathallan.co.uk/photo-gallery.php?id=15">
									<div class="overlay"></div><img src="images/image_galleries/thumbs/13503146881335439571IMG_8883.JPG" tppabs="http://www.strathallan.co.uk/images/image_galleries/thumbs/13503146881335439571IMG_8883.JPG" alt="#" />
								</a>
							</div>
						</div>	
                    	                    <div class="videoItem ">
							<h3>爱丁堡公爵</h3>
							<div class="vidSmall">
								<a href="photo-gallery.php-id=16.htm" tppabs="http://www.strathallan.co.uk/photo-gallery.php?id=16">
									<div class="overlay"></div><img src="images/image_galleries/thumbs/13503147181338473653Atthestart.JPG" tppabs="http://www.strathallan.co.uk/images/image_galleries/thumbs/13503147181338473653Atthestart.JPG" alt="#" />
								</a>
							</div>
						</div>	
                    	                    <div class="videoItemRight ">
							<h3>露营</h3>
							<div class="vidSmall">
								<a href="photo-gallery.php-id=17.htm" tppabs="http://www.strathallan.co.uk/photo-gallery.php?id=17">
									<div class="overlay"></div><img src="images/image_galleries/thumbs/13503147531342695573DSC_0661.JPG" tppabs="http://www.strathallan.co.uk/images/image_galleries/thumbs/13503147531342695573DSC_0661.JPG" alt="#" />
								</a>
							</div>
						</div>	
                    	                    <div class="videoItem ">
							<h3>表演</h3>
							<div class="vidSmall">
								<a href="photo-gallery.php-id=20.htm" tppabs="http://www.strathallan.co.uk/photo-gallery.php?id=20">
									<div class="overlay"></div><img src="images/image_galleries/thumbs/13503148161342706729DSC_4321.JPG" tppabs="http://www.strathallan.co.uk/images/image_galleries/thumbs/13503148161342706729DSC_4321.JPG" alt="#" />
								</a>
							</div>
						</div>	
                    	                    <div class="videoItem ">
							<h3>橄榄球比赛</h3>
							<div class="vidSmall">
								<a href="photo-gallery.php-id=21.htm" tppabs="http://www.strathallan.co.uk/photo-gallery.php?id=21">
									<div class="overlay"></div><img src="images/image_galleries/thumbs/13503148351347029915DSC_4687.JPG" tppabs="http://www.strathallan.co.uk/images/image_galleries/thumbs/13503148351347029915DSC_4687.JPG" alt="#" />
								</a>
							</div>
						</div>	
                    	                    <div class="videoItemRight ">
							<h3>拓展</h3>
							<div class="vidSmall">
								<a href="photo-gallery.php-id=22.htm" tppabs="http://www.strathallan.co.uk/photo-gallery.php?id=22">
									<div class="overlay"></div><img src="images/image_galleries/thumbs/13503148551348147217DSC01992.JPG" tppabs="http://www.strathallan.co.uk/images/image_galleries/thumbs/13503148551348147217DSC01992.JPG" alt="#" />
								</a>
							</div>
						</div>	
                    	                    <div class="videoItem ">
							<h3>少年军营</h3>
							<div class="vidSmall">
								<a href="photo-gallery.php-id=23.htm" tppabs="http://www.strathallan.co.uk/photo-gallery.php?id=23">
									<div class="overlay"></div><img src="images/image_galleries/thumbs/13503148761348740429DSC_4892.JPG" tppabs="http://www.strathallan.co.uk/images/image_galleries/thumbs/13503148761348740429DSC_4892.JPG" alt="#" />
								</a>
							</div>
						</div>	
                    	                    <div class="videoItem ">
							<h3>女生</h3>
							<div class="vidSmall">
								<a href="photo-gallery.php-id=25.htm" tppabs="http://www.strathallan.co.uk/photo-gallery.php?id=25">
									<div class="overlay"></div><img src="images/image_galleries/thumbs/13691610651368789303P1080667.JPG" tppabs="http://www.strathallan.co.uk/images/image_galleries/thumbs/13691610651368789303P1080667.JPG" alt="#" />
								</a>
							</div>
						</div>	
                    	                    <div class="videoItemRight ">
							<h3>水上游戏</h3>
							<div class="vidSmall">
								<a href="photo-gallery.php-id=29.htm" tppabs="http://www.strathallan.co.uk/photo-gallery.php?id=29">
									<div class="overlay"></div><img src="images/image_galleries/thumbs/1371571027P6167606.JPG" tppabs="http://www.strathallan.co.uk/images/image_galleries/thumbs/1371571027P6167606.JPG" alt="#" />
								</a>
							</div>
						</div>	
                    	                    <div class="videoItem ">
							<h3>演讲日</h3>
							<div class="vidSmall">
								<a href="photo-gallery.php-id=30.htm" tppabs="http://www.strathallan.co.uk/photo-gallery.php?id=30">
									<div class="overlay"></div><img src="images/image_galleries/thumbs/1371641903DSC_7522.JPG" tppabs="http://www.strathallan.co.uk/images/image_galleries/thumbs/1371641903DSC_7522.JPG" alt="#" />
								</a>
							</div>
						</div>	
                    	                    <div class="videoItem ">
							<h3>聚餐</h3>
							<div class="vidSmall">
								<a href="photo-gallery.php-id=31.htm" tppabs="http://www.strathallan.co.uk/photo-gallery.php?id=31">
									<div class="overlay"></div><img src="images/image_galleries/thumbs/1371646571DSCN0399.JPG" tppabs="http://www.strathallan.co.uk/images/image_galleries/thumbs/1371646571DSCN0399.JPG" alt="#" />
								</a>
							</div>
						</div>	
                    	                    <div class="videoItemRight ">
							<h3>戏剧表演</h3>
							<div class="vidSmall">
								<a href="photo-gallery.php-id=32.htm" tppabs="http://www.strathallan.co.uk/photo-gallery.php?id=32">
									<div class="overlay"></div><img src="images/image_galleries/thumbs/1371647003DSC_6517.JPG" tppabs="http://www.strathallan.co.uk/images/image_galleries/thumbs/1371647003DSC_6517.JPG" alt="#" />
								</a>
							</div>
						</div>	

